version: "3.9"

services:
  db:
    image: postgres:15    
    restart: always
    environment:
      POSTGRES_USER: bil_message_user
      POSTGRES_PASSWORD: bil_message_password
      POSTGRES_DB: bil_message_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
