@startuml
!define table(x) class x << (T,#FFAAAA) >>

skinparam linetype ortho

table(users) {
    <u>user_uuid</u> : UUID
    username : VARCHAR(50)
    nickname : VARCHAR(50)
    password_hash : VARCHAR(255)
    public_key : TEXT
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

table(chat_types) {
    <u>chat_type_uuid</u> : UUID
    name : VARCHAR(50)
    description : TEXT
}

table(chats) {
    <u>chat_uuid</u> : UUID
    name : VARCHAR(100)
    type_id : UUID
    created_by : UUID
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

table(chat_members) {
    <u>chat_uuid</u>
    <u>user_uuid</u>
    role : VARCHAR(20)
    joined_at : TIMESTAMP
}

table(messages) {
    <u>message_uuid</u> : UUID
    chat_id : UUID
    sender_id : UUID
    encrypted_text : TEXT
    created_at : TIMESTAMP    
}

table(message_keys) {
    <u>id</u> : UUID
    message_id : UUID
    recipient_id : UUID
    encrypted_symmetric_key : TEXT
    created_at : TIMESTAMP
}

table(message_reads) {
    <u>id</u> : UUID
    message_id : UUID
    user_id : UUID
    read_at : TIMESTAMP
}

' Связи
users "1" -down-> "0..*" chats : created_by
users "1" -down-> "0..*" chat_members : user_uuid
users "1" -down-> "0..*" messages : sender_id
users "1" -down-> "0..*" message_keys : recipient_id
users "1" -down-> "0..*" message_reads : user_id

chats "1" -down-> "0..*" chat_members : chat_uuid
chats "1" -down-> "0..*" messages : chat_id
chats "1" -down-> "1" chat_types : type_id

messages "1" -down-> "0..*" message_keys : message_id
messages "1" -down-> "0..*" message_reads : message_id

@enduml
