@startuml
skinparam linetype ortho
skinparam packageStyle rectangle

entity "users" as users {
  * user_uuid : UUID
  --
  username : varchar
  password_hash : text
  created_at : timestamp
  updated_at : timestamp
}

entity "user_devices" as user_devices {
  * device_uuid : UUID
  --
  user_uuid : UUID
  public_key : text
  created_at : timestamp
  updated_at : timestamp
}

entity "rooms" as rooms {
  * room_uuid : UUID
  --
  name : varchar
  creator_uuid : UUID
  created_at : timestamp
  updated_at : timestamp
}

entity "room_members" as room_members {
  * room_uuid : UUID
  * user_uuid : UUID
  --
  role : varchar
  joined_at : timestamp
  created_at : timestamp
  updated_at : timestamp
}

entity "room_keys" as room_keys {
  * room_uuid : UUID
  * device_uuid : UUID
  --
  encrypted_key : text
  created_at : timestamp
  updated_at : timestamp
}

entity "room_messages" as room_messages {
  * message_uuid : UUID
  --
  room_uuid : UUID
  sender_uuid : UUID
  ciphertext : text
  sent_at : timestamp
  created_at : timestamp
  updated_at : timestamp
}

' --- отношения ---
users ||--o{ user_devices : "owns"
users ||--o{ room_members : "joins"
users ||--o{ room_messages : "sends"
users ||--o{ rooms : "creates"

rooms ||--o{ room_members : "has"
rooms ||--o{ room_keys : "encrypts"
rooms ||--o{ room_messages : "contains"

user_devices ||--o{ room_keys : "stores"

@enduml
