@startuml
!define table(x) class x << (T,#FFAAAA) >>

skinparam linetype ortho

table(users) {
    <u>user_uuid</u> : TEXT
    username : TEXT    
    password_hash : TEXT
    public_key : TEXT
    created_at : DATETIME
    updated_at : DATETIME
}

table(devices) {
    <u>device_uuid</u> : TEXT
    user_uuid : TEXT
    public_key : TEXT
    created_at : DATETIME
    updated_at : DATETIME
}

table(chats) {
    <u>chat_uuid</u> : TEXT
    created_by_uuid : TEXT
    created_at : DATETIME
    updated_at : DATETIME
}

table(chat_members) {
    <u>chat_member_uuid</u> : TEXT
    chat_uuid : TEXT
    user_uuid : TEXT    
    joined_at : DATETIME
    created_at : DATETIME
    updated_at : DATETIME
}

table(messages) {
    <u>message_uuid</u> : TEXT
    chat_uuid : TEXT
    sender_uuid : TEXT
    encrypted_text : TEXT
    created_at : DATETIME    
    updated_at : DATETIME
}

table(message_keys) {
    <u>message_key_uuid</u> : TEXT
    message_uuid : TEXT
    device_uuid : TEXT
    encrypted_symmetric_key : TEXT
    created_at : DATETIME
    updated_at : DATETIME
}

table(message_reads) {
    <u>message_read_uuid</u> : TEXT
    message_uuid : TEXT
    user_uuid : TEXT
    read_at : DATETIME
    created_at : DATETIME
    updated_at : DATETIME
}

' Связи
users "1" --> "0..*" devices : user_uuid
users "1" --> "0..*" chats : created_by_uuid
users "1" --> "0..*" chat_members : user_uuid
users "1" --> "0..*" messages : sender_uuid
users "1" --> "0..*" message_reads : user_uuid

devices "1" --> "0..*" message_keys : device_uuid

chats "1" --> "0..*" chat_members : chat_uuid
chats "1" --> "0..*" messages : chat_uuid

messages "1" --> "0..*" message_keys : message_uuid
messages "1" --> "0..*" message_reads : message_uuid

@enduml
