@startuml
actor User
participant "Auth Service" as Auth
database "DB" as DB
participant "JWT Generator" as JWT

User -> Auth : Вводит username, password
Auth -> DB : Проверяет существование username
DB --> Auth : Существующий пользователь или nil

Auth -> Auth : Генерирует userUUID и clientUUID
Auth -> Auth : Хэширует пароль
Auth -> DB : Сохраняет пользователя 
DB --> Auth : Подтверждение сохранения пользователя
Auth -> JWT : Генерирует токен для clientUUID и userUUID
JWT --> Auth : JWT token
Auth --> User : Возвращает token
@enduml
