@startuml
actor User
participant "Auth Service" as Auth
database "DB" as DB

User -> Auth : Отправляет JSON {username, password}
Auth -> DB : Проверяет существование username
DB --> Auth : nil или существующий пользователь

Auth -> Auth : Генерирует userUUID
Auth -> Auth : Хэширует пароль
Auth -> DB : Сохраняет нового пользователя
DB --> Auth : Подтверждение сохранения
Auth --> User : userUUID
@enduml
