@startuml
title Удаление пользователя из комнаты

actor Client
participant Server

Client -> Server: DELETE /chat/{chat-uuid}/{member-uuid} {JWT}

Server -> Server: Проверка JWT
Server -> Server: Парсинг token, получение userUUID
Server -> Server: Проверка существования комнаты
Server -> Server: Проверка существования пользователя (memberUUID) в комнате
Server -> Server: Удаление пользователя из room_member
Server -> Server: Обновление ключа комнаты для E2EE (если необходимо)

Server --> Client: Подтверждение успешного удаления пользователя
@enduml
